<?php
/**
 * This class used to handling on fetching data from archive.org
 *
 * @author Nusagates <nusagates@gmail.com>
 */
class helper {
    private $source="https://archive.org/metadata/";
    /**
     * 
     * @param String $identifier is package data identifier generated by archive.org automatically 
     * @return String identifier
     * @example example/fetchData.php description
     */
    public function fetchData($source){
        return $this->source= str_replace("details", "metadata", $source);
    }
    /**
     * 
     * @return JSON Object
     */
    public function getResult(){
        #Set url for the package music want to fetched
        $json = file_get_contents($this->fetchData($this->source));
        #encode json
        $data = json_decode($json);
        #get directory for file
        $dir = $data->d1.$data->dir;
        #get music package identifier
        $identifier=$data->metadata->identifier;
        #get music package Title
        $title=$data->metadata->title;
        #get subject of the music package
        $subject=$data->metadata->subject;
        #get added date of the music package
        $addeddate=$data->metadata->addeddate;
        #get collection type of the music package
        $collection=$data->metadata->collection;

    }
}
