<?php
/**
 * This class used to handling on fetching data from archive.org
 *
 * @author Nusagates <nusagates@gmail.com>
 */
class helper {
    private $base_url="https://archive.org/metadata/";
    private $identifier;
    /**
     * 
     * @param String $identifier is package data identifier generated by archive.org automatically 
     * @return String identifier
     * @example example/fechData.php description
     */
    public function fetchData($identifier){
        return $this->identifier= $this->base_url.$identifier;
    }
    /**
     * 
     * @return JSON Object
     */
    public function getResult(){
        return $this->identifier;
    }
}
